import Foundation
struct AlertRuntimeState: Codable, Sendable, Equatable { var active = false; var lastFiredAt: Date?; var acknowledgedAt: Date?; var notificationActive: Bool? }
struct AlertEvaluation: Sendable { let states: [UUID: AlertRuntimeState]; let events: [InfrastructureEvent] }
enum AlertEngine {
    static func defaultRules(nodeID:UUID,peerTimeout:TimeInterval)->[AlertRule]{AlertRuleKind.allCases.map{kind in AlertRule(id:stableID(nodeID,kind.rawValue),nodeID:nodeID,kind:kind,enabled:true,threshold:kind == .disk || kind == .memory ? 90:kind == .ping ? 250:kind == .peerInactive ? peerTimeout:nil,severity:[.nodeOffline,.wireGuardOffline,.publicDNS,.newPublicListener,.configurationDrift].contains(kind) ? .critical:.warning,cooldown:900,muteUntil:nil,acknowledgedAt:nil)}}
    static func evaluate(rules:[AlertRule],conditions:[AlertRuleKind:Bool],previous:[UUID:AlertRuntimeState],now:Date=Date())->AlertEvaluation { var states=previous; var events:[InfrastructureEvent]=[]; for rule in rules where rule.enabled { var state=states[rule.id] ?? AlertRuntimeState(); let triggered=conditions[rule.kind] ?? false; if triggered && !state.active { let muted=rule.muteUntil.map{$0>now} ?? false; let cooled=state.lastFiredAt.map{now.timeIntervalSince($0)>=rule.cooldown} ?? true; state.active=true; state.notificationActive=false; if !muted && cooled { events.append(event(rule,now,false)); state.lastFiredAt=now; state.acknowledgedAt=nil; state.notificationActive=true } } else if !triggered && state.active { state.active=false; state.acknowledgedAt=nil; if state.notificationActive ?? true { events.append(event(rule,now,true)) }; state.notificationActive=false }; states[rule.id]=state }; return AlertEvaluation(states:states,events:events) }
    private static func event(_ rule:AlertRule,_ date:Date,_ recovery:Bool)->InfrastructureEvent { InfrastructureEvent(id:UUID(),nodeID:rule.nodeID,timestamp:date,componentID:"alert:\(rule.kind.rawValue)",kind:"alert",title:recovery ? "Recovered: \(rule.kind.rawValue)" : "Alert: \(rule.kind.rawValue)",detail:recovery ? "The observed condition cleared." : "The configured local rule is active.",state:recovery ? .online : rule.severity == .critical ? .critical : .warning,isRecovery:recovery) }
    static func stableID(_ nodeID:UUID,_ key:String)->UUID{var bytes=[UInt8](repeating:0,count:16);for(i,b)in(nodeID.uuidString+key).utf8.enumerated(){bytes[i%16]=bytes[i%16]&*31&+b};return UUID(uuid:(bytes[0],bytes[1],bytes[2],bytes[3],bytes[4],bytes[5],bytes[6],bytes[7],bytes[8],bytes[9],bytes[10],bytes[11],bytes[12],bytes[13],bytes[14],bytes[15]))}
}
