import SwiftUI

struct FleetOverviewView: View {
    @EnvironmentObject var model: AppViewModel
    private let columns = [GridItem(.adaptive(minimum: 330), spacing: 16)]
    var body: some View { ScrollView { if model.fleetSummaries.isEmpty { ContentUnavailableView("No infrastructure nodes", systemImage: "server.rack", description: Text("Save the current VPS in Settings to add the first node.")).padding(40) } else { LazyVGrid(columns: columns, alignment: .leading, spacing: 16) { ForEach(model.fleetSummaries) { node in Button { model.selectServer(node.id); model.selectedSection = .dashboard } label: { MetricCard(title: node.name, icon: "server.rack") { VStack(spacing: 8) { HStack { StatusDot(state: node.overall); Text(node.role).foregroundStyle(.secondary); Spacer(); Text(observationLabel(node)).fontWeight(.semibold) }; HStack { state("SSH", node.ssh); state("wg0", node.wireGuard); state("AdGuard", node.adGuard); state("AntiZapret", node.antiZapret) }; Divider(); HStack { metric("CPU", node.cpu); metric("RAM", node.memory); metric("Disk", node.disk); metric("Ping", node.ping, "ms") }; KeyValueRow(key: "Peers", value: node.peersOnline.map { "\($0)/\(node.peersTotal ?? 0)" } ?? "Unknown"); KeyValueRow(key: "Exposure warnings", value: String(node.exposureWarnings)); KeyValueRow(key: "Active incidents", value: String(node.activeIncidents)) } } }.buttonStyle(.plain) } }.padding(20) } } }
    private func state(_ name: String, _ value: HealthState) -> some View { VStack { StatusDot(state: value); Text(name).font(.caption2) }.frame(maxWidth: .infinity) }
    private func metric(_ name: String, _ value: Double?, _ suffix: String = "%") -> some View { VStack { Text(name).font(.caption2).foregroundStyle(.secondary); Text(value.map { String(format: "%.0f%@", $0, suffix) } ?? "—").monospacedDigit() }.frame(maxWidth: .infinity) }
    private func observationLabel(_ node: FleetNodeSummary) -> String { let freshness=ObservationFreshness(lastObservedAt:node.lastObservedAt,now:Date(),staleAfter:max(model.settings.pollingInterval*3,120));switch freshness.state{case .unknown:return "Unknown · never checked";case .stale:return "Stale · checked \(node.lastObservedAt!.formatted(.relative(presentation:.numeric)))";case .live:return "\(node.overall.rawValue.capitalized) · checked \(node.lastObservedAt!.formatted(.relative(presentation:.numeric)))"} }
}

struct TopologyView: View {
    @EnvironmentObject var model: AppViewModel
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: 16) { Text("Only relationships confirmed by the latest discovery are shown. Missing evidence remains Unknown.").foregroundStyle(.secondary); row("Internet", model.system.sshAvailable ? .online : .unknown, 0); row(model.activeNodeName, model.system.health, 1); row("SSH", model.system.sshAvailable ? .online : .unknown, 2); if model.wireGuard.state != .unknown { row("WireGuard \(model.wireGuard.interface)", model.wireGuard.state, 2, "\(model.wireGuard.peers.count) discovered peers") }; ForEach(model.units.filter { $0.name.localizedCaseInsensitiveContains("AdGuardHome") || $0.name == "antizapret.service" }) { unit in row(unit.name.localizedCaseInsensitiveContains("AdGuard") ? "AdGuard DNS" : "AntiZapret", unit.health, 2) }; ForEach(model.security.publicListeners.filter { $0.service.contains("OpenVPN") || ($0.service.contains("WireGuard") && $0.service != "Clean WireGuard") }) { endpoint in row(endpoint.service, endpoint.state, 2, "\(endpoint.protocolName):\(endpoint.port)") };if let home=model.home.network{Divider();row("Home Router",model.home.snapshot.mode == .homeLAN || model.home.snapshot.mode == .remote ? .online:.unknown,0,home.routerIP);row("Home LAN \(home.cidr)",model.home.snapshot.mode == .homeLAN || model.home.snapshot.mode == .remote ? .online:.unknown,1,"\(model.home.devices.count) known devices");ForEach(model.home.devices.filter{$0.isPinned}.prefix(8)){device in row(device.displayName,device.status == .online ? .online:device.status == .offline ? .offline:.unknown,2,device.ipv4 ?? device.ipv6)}} }.padding(24).frame(maxWidth: 720, alignment: .leading) } }
    private func row(_ title: String, _ state: HealthState, _ indent: Int, _ detail: String? = nil) -> some View { HStack { ForEach(0..<indent, id: \.self) { _ in Image(systemName: "arrow.turn.down.right").foregroundStyle(.tertiary) }; StatusDot(state: state); VStack(alignment: .leading) { Text(title).fontWeight(.semibold); if let detail { Text(detail).font(.caption).foregroundStyle(.secondary) } }; Spacer(); Text(state.rawValue.capitalized).foregroundStyle(.secondary) }.padding(10).background(.quaternary.opacity(0.35), in: RoundedRectangle(cornerRadius: 10)) }
}
