import AppKit
import SwiftUI

struct HomeAccessView:View{
    @EnvironmentObject var model:AppViewModel
    var body:some View{HomeAccessContentView(home:model.home)}
}

private struct HomeAccessContentView:View{
    @ObservedObject var home:HomeAccessController
    @StateObject private var state=HomeAccessScreenState()
    var body:some View{ScrollView{VStack(alignment:.leading,spacing:18){summary;configuration;devices;profiles}.padding(20)}
        .task{await home.load();state.reflect(home.network);await home.refresh();while !Task.isCancelled{try? await Task.sleep(for:.seconds(60));guard !Task.isCancelled else{break};await home.refresh()}}
        .onDisappear{Task{await home.stop()}}
        .sheet(item:$state.editingDevice){device in
            HomeDeviceEditor(device:device,loadHistory:{await home.observations(for:device.id)},refresh:{await home.refresh()}){updated in
                Task{await home.saveDevice(updated)}
            }
        }
        .sheet(isPresented:$state.addingDevice){ManualHomeDeviceSheet{value in Task{await home.addManual(name:value.name,type:value.type,ip:value.ip,mac:value.mac,hostname:value.hostname,notes:value.notes)}}}
        .sheet(isPresented:$state.qrVisible){if let image=state.qrImage{VStack(spacing:16){Text(state.qrName).font(.title2.bold());Image(nsImage:image).interpolation(.none).resizable().frame(width:360,height:360);Label("This QR contains private WireGuard configuration.",systemImage:"exclamationmark.triangle.fill").foregroundStyle(.red)}.padding(24)}}
        .confirmationDialog("Delete this device and its local observation history?",isPresented:$state.confirmDeviceDelete){Button("Delete",role:.destructive){if let id=state.pendingDeviceDelete{Task{await home.delete(id)}}};Button("Cancel",role:.cancel){}}
        .confirmationDialog("Delete this local Home Access profile?",isPresented:$state.confirmProfileDelete){Button("Delete",role:.destructive){if let profile=state.pendingProfileDelete{home.deleteProfile(profile)}};Button("Cancel",role:.cancel){}}
    }
    private var summary:some View{MetricCard(title:"Home status",icon:"house.and.flag.fill"){VStack(spacing:10){HStack{StatusDot(state:stateForMode(home.snapshot.mode));Text(home.snapshot.mode.rawValue).font(.title3.bold());Spacer();Button{Task{await home.refresh()}}label:{Label(home.isRefreshing ? "Refreshing…":"Refresh",systemImage:"arrow.clockwise")}.disabled(home.isRefreshing)};HStack{metric("Seen now",home.devices.filter{$0.status == .online}.count);metric("Known",home.devices.count);metric("Pinned",home.devices.filter(\.isPinned).count)};KeyValueRow(key:"Path",value:pathText);KeyValueRow(key:"Mac LAN",value:home.snapshot.macLANIP ?? "Unavailable");KeyValueRow(key:"Interface",value:home.snapshot.interface ?? "Unknown");KeyValueRow(key:"Gateway",value:home.snapshot.defaultGateway ?? "Unknown");KeyValueRow(key:"Last discovery",value:home.lastDiscovery?.formatted(.relative(presentation:.numeric)) ?? "Never");if let error=home.errorMessage{Text(error).foregroundStyle(.orange)}}}}
    private var configuration:some View{MetricCard(title:"Home Network Configuration",icon:"network"){VStack(alignment:.leading,spacing:10){TextField("Home Network Name",text:$state.networkName);TextField("Home LAN CIDR",text:$state.cidr);TextField("Router IP",text:$state.routerIP);TextField("Optional notes",text:$state.networkNotes);HStack{if let suggestion=home.snapshot.probableSubnet,state.cidr.isEmpty{Button("Use discovered \(suggestion)"){state.cidr=suggestion;if state.routerIP.isEmpty{state.routerIP=home.snapshot.defaultGateway ?? ""}}};Spacer();Button("Save Home Network"){Task{await home.saveNetwork(name:state.networkName,cidr:state.cidr,routerIP:state.routerIP,notes:state.networkNotes)}}.disabled(state.networkName.isEmpty || state.cidr.isEmpty)};Text("Discovery suggestions are not trusted until you save them. TunnelDeck never changes the router.").foregroundStyle(.secondary)}}}
    private var devices:some View{MetricCard(title:"Home Devices",icon:"desktopcomputer"){VStack(spacing:10){HStack{Picker("Filter",selection:$state.filter){ForEach(HomeDeviceFilter.allCases){Text($0.rawValue).tag($0)}}.labelsHidden().frame(width:130);TextField("Search name, IP, MAC, hostname or vendor",text:$state.search);Spacer();Button("Add Device Manually"){state.addingDevice=true};Button("Merge Selected…"){state.showMerge=true}.disabled(state.selection.count != 2)};if filteredDevices.isEmpty{ContentUnavailableView("No matching devices",systemImage:"network.slash",description:Text("Refresh while connected to a LAN, or add a device manually."))}else{Table(filteredDevices,selection:$state.selection){TableColumn("Status"){row in HStack{StatusDot(state:health(row.status));Text(row.status.rawValue.capitalized)}};TableColumn("Name",value:\.displayName);TableColumn("Type"){Text($0.customType ?? $0.type.rawValue)};TableColumn("IP"){Text($0.ipv4 ?? $0.ipv6 ?? "—").textSelection(.enabled)};TableColumn("MAC"){Text($0.macAddress ?? "—").textSelection(.enabled)};TableColumn("Hostname"){Text($0.hostname ?? "—")};TableColumn("Vendor"){Text($0.vendor ?? "Unknown")};TableColumn("Last Seen"){Text(HomePresence.label($0.lastSeen))}}.frame(minHeight:300);HStack{Button("Inspect / Edit"){state.editingDevice=state.selection.first.flatMap{id in home.devices.first{$0.id==id}}}.disabled(state.selection.count != 1);Button("Delete…",role:.destructive){state.pendingDeviceDelete=state.selection.first;state.confirmDeviceDelete=true}.disabled(state.selection.count != 1);Spacer()}}}.sheet(isPresented:$state.showMerge){HomeDeviceMergeSheet(devices:home.devices,selection:state.selection){source,destination in Task{await home.merge(source:source,into:destination)};state.showMerge=false}}}}
    private var profiles:some View{MetricCard(title:"Remote Access Profiles",icon:"lock.doc"){VStack(alignment:.leading,spacing:10){HStack{Button("Import WireGuard .conf…"){importProfile()};Button("Rename…"){state.renameProfile=selectedProfile;state.renameValue=selectedProfile?.url.deletingPathExtension().lastPathComponent ?? "";state.showRename=selectedProfile != nil}.disabled(selectedProfile==nil);Button("Reveal in Finder"){if let selectedProfile{ProfileStore.reveal(selectedProfile)}}.disabled(selectedProfile==nil);Button("Open with WireGuard"){if let selectedProfile{ProfileStore.open(selectedProfile)}}.disabled(selectedProfile==nil);Button("QR…"){if let selectedProfile{state.showQR(selectedProfile)}}.disabled(selectedProfile==nil);Button("Delete…",role:.destructive){state.pendingProfileDelete=selectedProfile;state.confirmProfileDelete=true}.disabled(selectedProfile==nil)};if home.profiles.isEmpty{Text("No imported Home Access profiles. Profiles stay local with mode 0600.").foregroundStyle(.secondary)}else{Table(home.profiles,selection:$state.profileSelection){TableColumn("Name",value:\.name);TableColumn("Type",value:\.type);TableColumn("Modified"){Text($0.modified.formatted())}}.frame(minHeight:150)};Text("LOCAL: Mac → Home LAN → Device\nREMOTE: Mac → verified Home Access route → Home Router → Device\nUNKNOWN: no verified route. CGNAT and relay transports are supported by the model but never assumed.").font(.caption).foregroundStyle(.secondary)}}.sheet(isPresented:$state.showRename){VStack(spacing:14){Text("Rename Home Access Profile").font(.headline);TextField("Name",text:$state.renameValue);HStack{Button("Cancel"){state.showRename=false};Button("Rename"){if let profile=state.renameProfile{home.renameProfile(profile,to:state.renameValue)};state.showRename=false}.disabled(!ProfileStore.validName(state.renameValue))}}.padding(24).frame(width:420)}}
    private var selectedProfile:LocalProfile?{state.profileSelection.first.flatMap{id in home.profiles.first{$0.id==id}}}
    private var filteredDevices:[HomeDevice]{home.devices.filter{device in let matchesFilter=switch state.filter{case .all:true;case .online:device.status == .online;case .offline:device.status == .offline;case .pinned:device.isPinned;case .unknown:device.status == .unknown};let q=state.search.lowercased();return matchesFilter && (q.isEmpty || [device.displayName,device.ipv4,device.ipv6,device.macAddress,device.hostname,device.vendor].compactMap{$0}.contains{$0.lowercased().contains(q)})}}
    private var pathText:String{switch home.snapshot.mode{case .homeLAN:"Mac → Home LAN → Device";case .remote:"Mac → Home Access VPN → Home Router → Device";case .other,.unknown:"No verified route to Home LAN"}}
    private func stateForMode(_ mode:HomeNetworkMode)->HealthState{switch mode{case .homeLAN,.remote:.online;case .other:.warning;case .unknown:.unknown}}
    private func health(_ value:HomeDeviceReachability)->HealthState{switch value{case .online:.online;case .offline:.offline;case .unknown:.unknown}}
    private func metric(_ title:String,_ value:Int)->some View{VStack{Text(String(value)).font(.title2.bold());Text(title).font(.caption).foregroundStyle(.secondary)}.frame(maxWidth:.infinity)}
    private func importProfile(){let panel=NSOpenPanel();panel.allowedContentTypes=[.init(filenameExtension:"conf")!];panel.allowsMultipleSelection=false;panel.canChooseDirectories=false;if panel.runModal() == .OK,let url=panel.url{Task{await home.importProfile(from:url)}}}
}

private enum HomeDeviceFilter:String,CaseIterable,Identifiable{case all="All",online="Online",offline="Offline",pinned="Pinned",unknown="Unknown";var id:String{rawValue}}
@MainActor private final class HomeAccessScreenState:ObservableObject{
    @Published var filter:HomeDeviceFilter = .all;@Published var search="";@Published var selection=Set<UUID>();@Published var profileSelection=Set<String>();@Published var networkName="Home";@Published var cidr="";@Published var routerIP="";@Published var networkNotes="";@Published var addingDevice=false;@Published var editingDevice:HomeDevice?;@Published var pendingDeviceDelete:UUID?;@Published var confirmDeviceDelete=false;@Published var showMerge=false;@Published var pendingProfileDelete:LocalProfile?;@Published var confirmProfileDelete=false;@Published var showRename=false;@Published var renameProfile:LocalProfile?;@Published var renameValue="";@Published var qrVisible=false;@Published var qrImage:NSImage?;@Published var qrName=""
    func reflect(_ network:HomeNetwork?){guard let network else{return};networkName=network.name;cidr=network.cidr;routerIP=network.routerIP;networkNotes=network.notes}
    func showQR(_ profile:LocalProfile){guard let content=try? ProfileStore.content(profile)else{return};qrName=profile.name;qrImage=ProfileStore.qrImage(for:content);qrVisible=qrImage != nil}
}

private struct ManualHomeDeviceValue{var name="";var type:HomeDeviceType = .unknown;var ip="";var mac="";var hostname="";var notes=""}
private struct ManualHomeDeviceSheet:View{@Environment(\.dismiss)var dismiss;@State private var value=ManualHomeDeviceValue();let save:(ManualHomeDeviceValue)->Void;var body:some View{VStack(alignment:.leading,spacing:14){Text("Add Home Device").font(.title2.bold());Form{TextField("Name",text:$value.name);Picker("Type",selection:$value.type){ForEach(HomeDeviceType.allCases){Text($0.rawValue).tag($0)}};TextField("IP (optional)",text:$value.ip);TextField("MAC (optional)",text:$value.mac);TextField("Hostname (optional)",text:$value.hostname);TextField("Notes",text:$value.notes)};HStack{Spacer();Button("Cancel"){dismiss()};Button("Add"){save(value);dismiss()}.buttonStyle(.borderedProminent).disabled(value.name.trimmingCharacters(in:.whitespaces).isEmpty)}}.padding(24).frame(width:500)}}

private struct HomeDeviceEditor:View{@Environment(\.dismiss)var dismiss;@State var device:HomeDevice;@State private var history:[HomeDeviceObservation]=[];let loadHistory:() async->[HomeDeviceObservation];let refresh:() async->Void;let save:(HomeDevice)->Void;var body:some View{VStack(alignment:.leading,spacing:14){Text("Home Device").font(.title2.bold());Form{TextField("Name",text:$device.displayName);Picker("Type",selection:$device.type){ForEach(HomeDeviceType.allCases){Text($0.rawValue).tag($0)}};if device.type == .custom{TextField("Custom type",text:optionalBinding(\.customType))};Toggle("Pinned",isOn:$device.isPinned);TextField("Notes",text:optionalBinding(\.notes));TextField("Preferred URL",text:optionalBinding(\.preferredAccessURL));TextField("Preferred SSH host",text:optionalBinding(\.preferredSSHHost));LabeledContent("IPv4",value:device.ipv4 ?? "—");LabeledContent("IPv6",value:device.ipv6 ?? "—");LabeledContent("MAC",value:device.macAddress ?? "—");LabeledContent("Hostname",value:device.hostname ?? "—");LabeledContent("Vendor",value:device.vendor ?? "Unknown");LabeledContent("Sources",value:device.discoverySources.map(\.rawValue).sorted().joined(separator:", "));LabeledContent("First seen",value:device.firstSeen.formatted());LabeledContent("Last seen",value:HomePresence.label(device.lastSeen));LabeledContent("Evidence",value:device.reachabilityEvidence ?? "Insufficient evidence")};GroupBox("Presence · last 30 days"){if history.isEmpty{Text("No confirmed observations").foregroundStyle(.secondary).frame(maxWidth:.infinity,alignment:.leading)}else{VStack(alignment:.leading){ForEach(history.suffix(8).reversed()){value in Text("\(HomePresence.label(value.timestamp)) · \(value.source.rawValue.uppercased()) · \(value.ip ?? "address unavailable")").font(.caption)}}.frame(maxWidth:.infinity,alignment:.leading)}};HStack{Button("Refresh Device"){Task{await refresh();history=await loadHistory()}};if let ip=device.ipv4 ?? device.ipv6{Button("Copy IP"){NSPasteboard.general.clearContents();NSPasteboard.general.setString(ip,forType:.string)}};if let value=device.preferredAccessURL,let url=URL(string:value){Button("Open Preferred URL"){NSWorkspace.shared.open(url)}};if let host=device.preferredSSHHost,let url=URL(string:"ssh://\(host)"){Button("SSH"){NSWorkspace.shared.open(url)}};Spacer();Button("Cancel"){dismiss()};Button("Save"){save(device);dismiss()}.buttonStyle(.borderedProminent)}}.padding(24).frame(width:600).task{history=await loadHistory()}}
    private func optionalBinding(_ keyPath:WritableKeyPath<HomeDevice,String?>)->Binding<String>{Binding(get:{device[keyPath:keyPath] ?? ""},set:{device[keyPath:keyPath]=$0.isEmpty ? nil:$0})}
}

private struct HomeDeviceMergeSheet:View{@Environment(\.dismiss)var dismiss;let devices:[HomeDevice];let selection:Set<UUID>;let merge:(UUID,UUID)->Void;@State private var destination:UUID?;var body:some View{VStack(alignment:.leading,spacing:14){Text("Merge Duplicate Devices").font(.title2.bold());Text("Choose the identity to keep. Addresses and observation history from the other identity will be retained.").foregroundStyle(.secondary);Picker("Keep",selection:$destination){Text("Choose…").tag(UUID?.none);ForEach(devices.filter{selection.contains($0.id)}){Text($0.displayName).tag(Optional($0.id))}};HStack{Spacer();Button("Cancel"){dismiss()};Button("Merge"){if let destination,let source=selection.first(where:{$0 != destination}){merge(source,destination)};dismiss()}.buttonStyle(.borderedProminent).disabled(destination==nil)}}.padding(24).frame(width:480)}}
