import SwiftUI

struct IncidentView: View {
    @EnvironmentObject var model: AppViewModel
    private var metrics: (day: Int, week: Int, downtime: TimeInterval, meanRecovery: TimeInterval?) { IncidentEngine.metrics(model.incidents) }
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: 16) { LazyVGrid(columns: [GridItem(.adaptive(minimum: 170))]) { tile("Active", model.incidents.filter { $0.recoveryState == .active }.count.description); tile("Incidents · 24h", metrics.day.description); tile("Incidents · 7d", metrics.week.description); tile("VPS downtime · 24h", duration(metrics.downtime)); tile("Mean recovery", metrics.meanRecovery.map(duration) ?? "—") }; ForEach(model.incidents.reversed()) { incident in MetricCard(title: incident.observableCondition, icon: incident.recoveryState == .active ? "exclamationmark.triangle.fill" : "checkmark.circle") { VStack(alignment: .leading, spacing: 7) { KeyValueRow(key: "Start", value: incident.startedAt.formatted()); KeyValueRow(key: "End", value: incident.endedAt?.formatted() ?? "Active"); KeyValueRow(key: "Duration", value: duration(incident.duration)); KeyValueRow(key: "Recovered", value: incident.recoveryState == .recovered ? "Yes" : "No"); KeyValueRow(key: "Affected", value: incident.affectedComponents.joined(separator: ", ")); Text("Observable condition — not asserted root cause").font(.caption).foregroundStyle(.secondary); ForEach(incident.timeline) { entry in HStack { StatusDot(state: entry.state); Text(entry.timestamp.formatted(date: .omitted, time: .standard)).monospacedDigit(); Text(entry.message) } } } } } }.padding(20) } }
    private func tile(_ title: String, _ value: String) -> some View { MetricCard(title: title, icon: "chart.bar") { Text(value).font(.title2.bold()).monospacedDigit() } }
    private func duration(_ interval: TimeInterval) -> String { let seconds = max(0, Int(interval)); return seconds >= 3600 ? "\(seconds / 3600)h \((seconds % 3600) / 60)m" : "\(seconds / 60)m" }
}
